# ============================================================
# Dovecot 마스터 프로세스 설정 -- 군 웹메일 서버
# ============================================================

service imap-login {
  inet_listener imap {
    port = 143
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
  unix_listener auth-userdb {
    mode = 0600
    user = vmail
  }
}
