FROM node:20-alpine

WORKDIR /app

COPY assets/01_external_portal/src/frontend/package.json .
RUN npm install --legacy-peer-deps

COPY assets/01_external_portal/src/frontend/ .
RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
