-- Create roles
CREATE ROLE app_service WITH SUPERUSER LOGIN PASSWORD 'Sup3rS3cr3t!' CREATEDB CREATEROLE;
CREATE ROLE portal_app WITH LOGIN PASSWORD 'P0rtal#DB@2026!' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE portal_ro WITH LOGIN PASSWORD 'Portal_R3ad0nly@2026' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE complaint_rw WITH LOGIN PASSWORD 'Compl@int_RW_2026!' NOSUPERUSER NOCREATEDB NOCREATEROLE;

-- Create databases
CREATE DATABASE mois_portal OWNER postgres ENCODING 'UTF8' TEMPLATE template0;
CREATE DATABASE agency_db OWNER postgres ENCODING 'UTF8' TEMPLATE template0;
CREATE DATABASE complaint_db OWNER postgres ENCODING 'UTF8' TEMPLATE template0;

-- Grant connects
GRANT CONNECT ON DATABASE mois_portal TO portal_app;
GRANT CONNECT ON DATABASE mois_portal TO portal_ro;
GRANT CONNECT ON DATABASE complaint_db TO complaint_rw;
